openapi: 3.0.1
servers:
  - description: Production URL
    url: https://marketplace.walmartapis.com
  - description: Sandbox URL
    url: https://sandbox.walmartapis.com
info:
  contact:
    x-twitter: Walmart
  description: The price is a fundamental building block for your listing on Walmart.com. You can use the price management APIs to set up and manage the price for a given item
  title: Price Management
  version: 1.0.0
  x-apisguru-categories:
    - ecommerce
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_Walmart_profile_image.jpeg
  x-origin:
    - format: openapi
      url: https://developer.walmart.com/api/detail
      version: "3.0"
  x-providerName: walmart.com
  x-serviceName: price
security:
  - {}
paths:
  /v3/cppreference:
    post:
      description: |-
        This API helps Sellers to completely opt-in or opt-out from CAP program.

        If the subsidyEnrolled value = "true", the Seller enrolls in the CAP program. All eligible SKUs (current and future) are by default opt-in. Seller should use the SKU opt-in/opt-out API to opt-out individual items.

        If the subsidyEnrolled value = "false", the Seller stops participating in the CAP program and all eligible SKUs (current and future) are opt-out of the CAP program.
      externalDocs:
        description: View Guide
        url: /doc/us/mp/us-mp-price/#1290
      operationId: optCapProgramInPrice
      parameters:
        - description: The access token retrieved in the Token API call
          example: eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM.....
          in: header
          name: WM_SEC.ACCESS_TOKEN
          required: true
          schema:
            type: string
        - description: A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: false
          schema:
            type: string
        - description: A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID
          example: b3261d2d-028a-4ef7-8602-633c23200af6
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
        - description: Walmart Service Name
          example: Walmart Service Name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                subsidyEnrolled:
                  description: A Boolean parameter that allows all sellers to completely enroll in or out of the Competitive Price Adjustment program
                  type: boolean
                subsidyPreference:
                  description: A Boolean parameter that determines whether offer level subsidy setting override seller level subsidy setting
                  type: boolean
              type: object
        description: Request fields
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  martId:
                    description: A unique ID that a user or seller uses for a marketplace.
                    type: string
                  statusInfo:
                    properties:
                      subsidyEnrolled:
                        description: A Boolean parameter that allows all sellers to completely enroll in or out of the Competitive Price Adjustment program
                        type: boolean
                      subsidyPreference:
                        description: A Boolean parameter that determines whether offer level subsidy setting override seller level subsidy setting
                        type: boolean
                    type: object
                type: object
          description: Successful Operation
      summary: Set up CAP SKU All
      tags:
        - Prices
  /v3/feeds:
    post:
      description: |-
        Updates prices in bulk.

        In one Feed you can update up to 10,000 items in bulk. To ensure optimal Feed processing time, we recommend sending no more than 1000 items in one Feed and keeping the Feed sizes below 10 MB.

        The price sequence guarantee is observed by the bulk price update functionality, subject to the following rules:

        The timestamp used to determine precedence is passed in the request headers. All price updates in the feed are considered to have the same timestamp. The timestamp in the XML file is used only for auditing.
        You can send a single SKU multiple times in one Feed. If a SKU is repeated in a Feed, the price will be set for that SKU on Walmart.com, but there is no guarantee as to which SKU's price within that feed will be used.
        This API should be used in preference to the update a price. It should be called no sooner than 24 hours after a new item is set up and a wpid (Walmart Part ID) is available. Thereafter, the bulk price update has an service level agreement (SLA) of 15 minutes.

        After the update is submitted, wait for at least five minutes before verifying whether the bulk price update was successful. Individual SKU price update success or failure is only available after the entire feed is processed.

        If a SKU's price update fails (for example, multiple price updates were sent for the same SKU in a single feed), an error will be returned.
      operationId: priceBulkUploads
      parameters:
        - description: The feed Type
          in: query
          name: feedType
          required: true
          schema:
            enum:
              - price
              - CPT_SELLER_ELIGIBILITY
            type: string
        - description: The access token retrieved in the Token API call
          example: eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM.....
          in: header
          name: WM_SEC.ACCESS_TOKEN
          required: true
          schema:
            type: string
        - description: A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: false
          schema:
            type: string
        - description: A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID
          example: b3261d2d-028a-4ef7-8602-633c23200af6
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
        - description: Walmart Service Name
          example: Walmart Service Name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            examples:
              json1:
                value:
                  Price:
                    - pricing:
                        - comparisonPrice:
                            amount: 4.99
                            currency: USD
                          comparisonPriceType: BASE
                          currentPrice:
                            amount: 3
                            currency: USD
                          currentPriceType: REDUCED
                      sku: 30348_KFTest
                    - pricing:
                        - comparisonPrice:
                            amount: 4.99
                            currency: USD
                          comparisonPriceType: BASE
                          currentPrice:
                            amount: 3
                            currency: USD
                          currentPriceType: REDUCED
                      sku: OT-PP7F-QGUG
                  PriceHeader:
                    version: "1.7"
              xml1:
                value: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <PriceFeed xmlns="http://walmart.com/">
                      <PriceHeader>
                          <version>1.5.1</version>
                      </PriceHeader>
                      <Price>
                          <itemIdentifier>
                              <sku>30348_KFTest</sku>
                          </itemIdentifier>
                          <pricingList>
                              <pricing>
                                  <currentPrice>
                                      <value currency="USD" amount="4.00"/>
                                  </currentPrice>
                              </pricing>
                          </pricingList>
                      </Price>
                      <Price>
                          <itemIdentifier>
                              <sku>OT-PP7F-QGUG</sku>
                          </itemIdentifier>
                          <pricingList>
                              <pricing>
                                  <currentPrice>
                                      <value currency="USD" amount="4.00"/>
                                  </currentPrice>
                              </pricing>
                          </pricingList>
                      </Price>
                  </PriceFeed>
            schema:
              properties:
                file:
                  description: Feed file to upload
                  format: binary
                  type: string
              required:
                - file
              type: object
        description: "The request body consists of a Feed file attached to the request based on the feedType selected "
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                feedId: 14066B6642344B76A8B77AC094F8C63B@AVMBAgA
              schema:
                properties:
                  additionalAttributes:
                    nullable: true
                    type: object
                  errors:
                    nullable: true
                    type: object
                  feedId:
                    description: A unique ID, returned from the Bulk Upload API, used for tracking the feed file
                    type: string
                type: object
            application/xml:
              example: |-
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <ns2:FeedAcknowledgement xmlns:ns2="http://walmart.com/">
                    <ns2:feedId>55DE8A53B09F41BBBF261C1AB5FB2BC8@AVMBAgA</ns2:feedId>
                </ns2:FeedAcknowledgement>
              schema:
                properties:
                  additionalAttributes:
                    nullable: true
                    type: object
                  errors:
                    nullable: true
                    type: object
                  feedId:
                    description: A unique ID, returned from the Bulk Upload API, used for tracking the feed file
                    type: string
                type: object
          description: Successful Operation
      summary: Update bulk prices (Multiple)
      tags:
        - Prices
  /v3/price:
    put:
      description: Updates the regular price for a given item.
      operationId: updatePrice
      parameters:
        - description: The access token retrieved in the Token API call
          example: eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM.....
          in: header
          name: WM_SEC.ACCESS_TOKEN
          required: true
          schema:
            type: string
        - description: A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: false
          schema:
            type: string
        - description: A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID
          example: b3261d2d-028a-4ef7-8602-633c23200af6
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
        - description: Walmart Service Name
          example: Walmart Service Name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              pricing:
                - currentPrice:
                    amount: 10
                    currency: USD
                  currentPriceType: BASE
              sku: 97964_KFTest
            schema:
              properties:
                definitions:
                  type: object
                offerId:
                  description: This is applicable only for promotions
                  type: string
                pricing:
                  items:
                    properties:
                      comparisonPrice:
                        description: This is applicable only for promotions
                        properties:
                          amount:
                            format: double
                            type: number
                          currency:
                            enum:
                              - USD
                              - CAD
                            type: string
                        type: object
                      comparisonPriceType:
                        description: This is applicable only for promotions
                        enum:
                          - BASE
                        type: string
                      currentPrice:
                        properties:
                          amount:
                            format: double
                            type: number
                          currency:
                            enum:
                              - USD
                              - CAD
                            type: string
                        type: object
                      currentPriceType:
                        description: This is applicable only for both promotions and price
                        enum:
                          - BASE
                          - REDUCED
                          - CLEARANCE
                        type: string
                      effectiveDate:
                        description: This is applicable only for promotions
                        format: date-time
                        type: string
                      expirationDate:
                        description: This is applicable only for promotions
                        format: date-time
                        type: string
                      priceDisplayCodes:
                        description: Represent promo placement. This is applicable only for promotions
                        enum:
                          - CART
                          - CHECKOUT
                        type: string
                      processMode:
                        description: This is applicable only for promotions
                        enum:
                          - UPSERT
                          - DELETE
                        type: string
                      promoId:
                        description: This is applicable only for promotions
                        type: string
                    required:
                      - currentPrice
                      - currentPriceType
                    type: object
                  type: array
                replaceAll:
                  description: This is applicable only for promotions
                  enum:
                    - "true"
                    - "false"
                  type: string
                sku:
                  type: string
              required:
                - pricing
                - sku
              type: object
        description: The request body consists of a Feed file attached to the request.
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                ItemPriceResponse:
                  mart: WALMART_US
                  message: Thank you. Your price has been updated. Please allow up to five minutes for this change to be reflected on the site.
                  sku: 97964_KFTest
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        category:
                          enum:
                            - APPLICATION
                            - SYSTEM
                            - REQUEST
                            - DATA
                          type: string
                        causes:
                          items:
                            properties:
                              code:
                                type: string
                              description:
                                type: string
                              field:
                                type: string
                              type:
                                type: string
                            type: object
                            xml:
                              name: Cause
                          type: array
                          xml:
                            wrapped: true
                        code:
                          type: string
                        component:
                          type: string
                        description:
                          type: string
                        errorIdentifiers:
                          additionalProperties:
                            type: object
                          type: object
                        field:
                          type: string
                        gatewayErrorCategory:
                          enum:
                            - INTERNAL_DATA_ERROR
                            - EXTERNAL_DATA_ERROR
                            - SYSTEM_ERROR
                          type: string
                        info:
                          type: string
                        serviceName:
                          type: string
                        severity:
                          enum:
                            - INFO
                            - WARN
                            - ERROR
                          type: string
                        type:
                          type: string
                      required:
                        - code
                      type: object
                      xml:
                        name: GatewayError
                    type: array
                    xml:
                      name: error
                  mart:
                    description: "Marketplace name. Example: Walmart-US"
                    type: string
                    xml:
                      namespace: http://walmart.com/
                  message:
                    description: A message of acknowledgement for a price update
                    type: string
                    xml:
                      namespace: http://walmart.com/
                  sku:
                    description: An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.
                    type: string
                    xml:
                      namespace: http://walmart.com/
                  statusCode:
                    format: int32
                    type: integer
                type: object
                xml:
                  name: ItemPriceResponse
                  namespace: http://walmart.com/
            application/xml:
              example: |
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <ns2:ItemPriceResponse xmlns:ns2="http://walmart.com/">
                    <ns2:mart>WALMART_US</ns2:mart>
                    <ns2:sku>97964_KFTest</ns2:sku>
                    <ns2:message>Thank you. Your price has been updated. Please allow up to five minutes for this change to be reflected on the site.</ns2:message>
                </ns2:ItemPriceResponse>
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        category:
                          enum:
                            - APPLICATION
                            - SYSTEM
                            - REQUEST
                            - DATA
                          type: string
                        causes:
                          items:
                            properties:
                              code:
                                type: string
                              description:
                                type: string
                              field:
                                type: string
                              type:
                                type: string
                            type: object
                            xml:
                              name: Cause
                          type: array
                          xml:
                            wrapped: true
                        code:
                          type: string
                        component:
                          type: string
                        description:
                          type: string
                        errorIdentifiers:
                          additionalProperties:
                            type: object
                          type: object
                        field:
                          type: string
                        gatewayErrorCategory:
                          enum:
                            - INTERNAL_DATA_ERROR
                            - EXTERNAL_DATA_ERROR
                            - SYSTEM_ERROR
                          type: string
                        info:
                          type: string
                        serviceName:
                          type: string
                        severity:
                          enum:
                            - INFO
                            - WARN
                            - ERROR
                          type: string
                        type:
                          type: string
                      required:
                        - code
                      type: object
                      xml:
                        name: GatewayError
                    type: array
                    xml:
                      name: error
                  mart:
                    description: "Marketplace name. Example: Walmart-US"
                    type: string
                    xml:
                      namespace: http://walmart.com/
                  message:
                    description: A message of acknowledgement for a price update
                    type: string
                    xml:
                      namespace: http://walmart.com/
                  sku:
                    description: An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.
                    type: string
                    xml:
                      namespace: http://walmart.com/
                  statusCode:
                    format: int32
                    type: integer
                type: object
                xml:
                  name: ItemPriceResponse
                  namespace: http://walmart.com/
          description: Successful Operation
      summary: Update a price
      tags:
        - Prices
components:
  parameters:
    accept:
      description: "Only supported Media Type : application/json"
      example: application/json
      in: header
      name: Accept
      required: true
      schema:
        type: string
    accessToken:
      description: The access token retrieved in the Token API call
      example: eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM.....
      in: header
      name: WM_SEC.ACCESS_TOKEN
      required: true
      schema:
        type: string
    authorization:
      description: Basic authorization header. Base 64 encodes the Client ID and Client Secret retrieved in step two of the integration steps.
      example: Basic YzcyOTFjNmItNzI5MC00....
      in: header
      name: Authorization
      required: true
      schema:
        type: string
    channelType:
      description: A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding
      in: header
      name: WM_CONSUMER.CHANNEL.TYPE
      required: false
      schema:
        type: string
    content-type:
      description: "Only supported Media Type : application/json"
      example: application/json
      in: header
      name: Content-Type
      required: true
      schema:
        type: string
    correlationId:
      description: A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID
      example: b3261d2d-028a-4ef7-8602-633c23200af6
      in: header
      name: WM_QOS.CORRELATION_ID
      required: true
      schema:
        type: string
    svcName:
      description: Walmart Service Name
      example: Walmart Service Name
      in: header
      name: WM_SVC.NAME
      required: true
      schema:
        type: string
  schemas:
    CapProgramResponse:
      properties:
        martId:
          description: A unique ID that a user or seller uses for a marketplace.
          type: string
        statusInfo:
          properties:
            subsidyEnrolled:
              description: A Boolean parameter that allows all sellers to completely enroll in or out of the Competitive Price Adjustment program
              type: boolean
            subsidyPreference:
              description: A Boolean parameter that determines whether offer level subsidy setting override seller level subsidy setting
              type: boolean
          type: object
      type: object
    Cause:
      properties:
        code:
          type: string
        description:
          type: string
        field:
          type: string
        type:
          type: string
      type: object
      xml:
        name: Cause
    ComparisonPrice:
      description: This is applicable only for promotions
      properties:
        amount:
          format: double
          type: number
        currency:
          enum:
            - USD
            - CAD
          type: string
      type: object
    CurrentPrice:
      properties:
        amount:
          format: double
          type: number
        currency:
          enum:
            - USD
            - CAD
          type: string
      type: object
    FeedId:
      properties:
        additionalAttributes:
          nullable: true
          type: object
        errors:
          nullable: true
          type: object
        feedId:
          description: A unique ID, returned from the Bulk Upload API, used for tracking the feed file
          type: string
      type: object
    GatewayError:
      properties:
        category:
          enum:
            - APPLICATION
            - SYSTEM
            - REQUEST
            - DATA
          type: string
        causes:
          items:
            properties:
              code:
                type: string
              description:
                type: string
              field:
                type: string
              type:
                type: string
            type: object
            xml:
              name: Cause
          type: array
          xml:
            wrapped: true
        code:
          type: string
        component:
          type: string
        description:
          type: string
        errorIdentifiers:
          additionalProperties:
            type: object
          type: object
        field:
          type: string
        gatewayErrorCategory:
          enum:
            - INTERNAL_DATA_ERROR
            - EXTERNAL_DATA_ERROR
            - SYSTEM_ERROR
          type: string
        info:
          type: string
        serviceName:
          type: string
        severity:
          enum:
            - INFO
            - WARN
            - ERROR
          type: string
        type:
          type: string
      required:
        - code
      type: object
      xml:
        name: GatewayError
    ItemPriceResponse:
      properties:
        errors:
          items:
            properties:
              category:
                enum:
                  - APPLICATION
                  - SYSTEM
                  - REQUEST
                  - DATA
                type: string
              causes:
                items:
                  properties:
                    code:
                      type: string
                    description:
                      type: string
                    field:
                      type: string
                    type:
                      type: string
                  type: object
                  xml:
                    name: Cause
                type: array
                xml:
                  wrapped: true
              code:
                type: string
              component:
                type: string
              description:
                type: string
              errorIdentifiers:
                additionalProperties:
                  type: object
                type: object
              field:
                type: string
              gatewayErrorCategory:
                enum:
                  - INTERNAL_DATA_ERROR
                  - EXTERNAL_DATA_ERROR
                  - SYSTEM_ERROR
                type: string
              info:
                type: string
              serviceName:
                type: string
              severity:
                enum:
                  - INFO
                  - WARN
                  - ERROR
                type: string
              type:
                type: string
            required:
              - code
            type: object
            xml:
              name: GatewayError
          type: array
          xml:
            name: error
        mart:
          description: "Marketplace name. Example: Walmart-US"
          type: string
          xml:
            namespace: http://walmart.com/
        message:
          description: A message of acknowledgement for a price update
          type: string
          xml:
            namespace: http://walmart.com/
        sku:
          description: An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.
          type: string
          xml:
            namespace: http://walmart.com/
        statusCode:
          format: int32
          type: integer
      type: object
      xml:
        name: ItemPriceResponse
        namespace: http://walmart.com/
    Price:
      properties:
        definitions:
          type: object
        offerId:
          description: This is applicable only for promotions
          type: string
        pricing:
          items:
            properties:
              comparisonPrice:
                description: This is applicable only for promotions
                properties:
                  amount:
                    format: double
                    type: number
                  currency:
                    enum:
                      - USD
                      - CAD
                    type: string
                type: object
              comparisonPriceType:
                description: This is applicable only for promotions
                enum:
                  - BASE
                type: string
              currentPrice:
                properties:
                  amount:
                    format: double
                    type: number
                  currency:
                    enum:
                      - USD
                      - CAD
                    type: string
                type: object
              currentPriceType:
                description: This is applicable only for both promotions and price
                enum:
                  - BASE
                  - REDUCED
                  - CLEARANCE
                type: string
              effectiveDate:
                description: This is applicable only for promotions
                format: date-time
                type: string
              expirationDate:
                description: This is applicable only for promotions
                format: date-time
                type: string
              priceDisplayCodes:
                description: Represent promo placement. This is applicable only for promotions
                enum:
                  - CART
                  - CHECKOUT
                type: string
              processMode:
                description: This is applicable only for promotions
                enum:
                  - UPSERT
                  - DELETE
                type: string
              promoId:
                description: This is applicable only for promotions
                type: string
            required:
              - currentPrice
              - currentPriceType
            type: object
          type: array
        replaceAll:
          description: This is applicable only for promotions
          enum:
            - "true"
            - "false"
          type: string
        sku:
          type: string
      required:
        - pricing
        - sku
      type: object
    Pricing:
      properties:
        comparisonPrice:
          description: This is applicable only for promotions
          properties:
            amount:
              format: double
              type: number
            currency:
              enum:
                - USD
                - CAD
              type: string
          type: object
        comparisonPriceType:
          description: This is applicable only for promotions
          enum:
            - BASE
          type: string
        currentPrice:
          properties:
            amount:
              format: double
              type: number
            currency:
              enum:
                - USD
                - CAD
              type: string
          type: object
        currentPriceType:
          description: This is applicable only for both promotions and price
          enum:
            - BASE
            - REDUCED
            - CLEARANCE
          type: string
        effectiveDate:
          description: This is applicable only for promotions
          format: date-time
          type: string
        expirationDate:
          description: This is applicable only for promotions
          format: date-time
          type: string
        priceDisplayCodes:
          description: Represent promo placement. This is applicable only for promotions
          enum:
            - CART
            - CHECKOUT
          type: string
        processMode:
          description: This is applicable only for promotions
          enum:
            - UPSERT
            - DELETE
          type: string
        promoId:
          description: This is applicable only for promotions
          type: string
      required:
        - currentPrice
        - currentPriceType
      type: object
    StatusInfo:
      properties:
        subsidyEnrolled:
          description: A Boolean parameter that allows all sellers to completely enroll in or out of the Competitive Price Adjustment program
          type: boolean
        subsidyPreference:
          description: A Boolean parameter that determines whether offer level subsidy setting override seller level subsidy setting
          type: boolean
      type: object
