openapi: 3.0.0
servers:
  - url: 'https://canada-holidays.ca'
info:
  contact:
    email: paul@pcraig3.ca
    name: Paul Craig
    url: 'https://canada-holidays.ca/feedback'
  description: 'This API that lists all 28 public holidays for all 13 provinces and territories in Canada, including federal holidays.'
  license:
    name: MIT
    url: 'https://github.com/pcraig3/hols/blob/master/LICENSE'
  title: Canada Holidays
  version: '1.0'
  x-apisguru-categories:
    - open_data
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg'
  x-origin:
    - format: openapi
      url: 'https://api.swaggerhub.com/apis/pcraig3/canada-holidays/1.0'
      version: '3.0'
  x-providerName: canada-holidays.ca
tags:
  - description: Get holiday(s) with associated provinces
    name: holidays
  - description: Get province(s) with associated holidays
    name: provinces
  - description: Get welcome message and links
    name: root
paths:
  /api/v1:
    get:
      description: Returns a welcome message.
      operationId: get-api-vi
      responses:
        '200':
          content:
            application/json:
              examples:
                /:
                  value:
                    _links:
                      holidays:
                        href: 'http://localhost:3000/api/v1/holidays'
                      provinces:
                        href: 'http://localhost:3000/api/v1/provinces'
                      self:
                        href: 'http://localhost:3000/api/v1/'
                    message: Hello / Bonjour! Welcome to the Canada Holidays API / Bienvenue dans l’API canadienne des jours fériés
              schema:
                properties:
                  _links:
                    properties:
                      holidays:
                        properties:
                          href:
                            description: Domain to get all holidays
                            example: 'http://localhost:3000/api/v1/holidays'
                            type: string
                        type: object
                      provinces:
                        properties:
                          href:
                            description: Domain to get all provinces
                            example: 'http://localhost:3000/api/v1/provinces'
                            type: string
                        type: object
                      self:
                        properties:
                          href:
                            description: Root domain
                            example: 'http://localhost:3000/api/v1/'
                            type: string
                        type: object
                    type: object
                  message:
                    description: A welcome message
                    example: Hello / Bonjour!
                    type: string
                type: object
          description: OK
      summary: root
      tags:
        - root
  /api/v1/holidays:
    get:
      description: Returns Canadian public holidays. Each holiday lists the regions that observe it.
      operationId: get-api-v1-holidays
      parameters:
        - allowEmptyValue: true
          description: A calendar year
          in: query
          name: year
          schema:
            default: '2020'
            maxLength: 4
            minLength: 4
            pattern: '^\d{4}$'
            type: string
        - allowEmptyValue: true
          description: 'A boolean parameter. If true, will return only federal holidays. If false, will return no federal holidays.'
          in: query
          name: federal
          schema:
            enum:
              - '1'
              - '0'
              - 'true'
              - 'false'
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                /holidays:
                  value:
                    holidays:
                      - date: '2020-01-01'
                        federal: 1
                        id: 1
                        nameEn: New Year’s Day
                        nameFr: Jour de l’An
                        provinces:
                          - id: AB
                            nameEn: Alberta
                            nameFr: Alberta
                          - id: BC
                            nameEn: British Columbia
                            nameFr: Colombie-Britannique
                          - id: MB
                            nameEn: Manitoba
                            nameFr: Manitoba
                          - id: NB
                            nameEn: New Brunswick
                            nameFr: Nouveau-Brunswick
                          - id: NL
                            nameEn: Newfoundland and Labrador
                            nameFr: Terre-Neuve-et-Labrador
                          - id: NT
                            nameEn: Northwest Territories
                            nameFr: Territoires du Nord-Ouest
                          - id: NS
                            nameEn: Nova Scotia
                            nameFr: Nouvelle-Écosse
                          - id: NU
                            nameEn: Nunavut
                            nameFr: Nunavut
                          - id: 'ON'
                            nameEn: Ontario
                            nameFr: Ontario
                          - id: PE
                            nameEn: Prince Edward Island
                            nameFr: Île-du-Prince-Édouard
                          - id: QC
                            nameEn: Quebec
                            nameFr: Québec
                          - id: SK
                            nameEn: Saskatchewan
                            nameFr: Saskatchewan
                          - id: YT
                            nameEn: Yukon
                            nameFr: Yukon
                      - date: '2020-02-17'
                        federal: 0
                        id: 2
                        nameEn: Louis Riel Day
                        nameFr: Journée Louis Riel
                        provinces:
                          - id: MB
                            nameEn: Manitoba
                            nameFr: Manitoba
              schema:
                properties:
                  holidays:
                    items:
                      $ref: '#/components/schemas/Holiday'
                    type: array
                type: object
          description: OK
          headers: {}
      summary: Get all holidays
      tags:
        - holidays
  '/api/v1/holidays/{holidayId}':
    get:
      description: Returns one Canadian statutory holiday by integer id. Returns a 404 response for invalid ids.
      operationId: get-holidays-holidayId
      parameters:
        - allowEmptyValue: true
          description: A calendar year
          in: query
          name: year
          schema:
            default: '2020'
            maxLength: 4
            minLength: 4
            pattern: '^\d{4}$'
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                /holidays/2:
                  value:
                    holiday:
                      date: '2020-02-17'
                      federal: 0
                      id: 2
                      nameEn: Louis Riel Day
                      nameFr: Journée Louis Riel
                      provinces:
                        - id: MB
                          nameEn: Manitoba
                          nameFr: Manitoba
              schema:
                properties:
                  holiday:
                    $ref: '#/components/schemas/Holiday'
                type: object
          description: OK
          headers: {}
        '404':
          content:
            application/json:
              examples:
                /holidays/100:
                  value:
                    error:
                      message: 'Error: No holiday with id “100”'
                      status: 404
                      timestamp: '2020-04-27T05:41:10.710Z'
              schema:
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
                type: object
          description: Not Found
      summary: Get a holiday by id
      tags:
        - holidays
    parameters:
      - description: Primary key for a holiday
        in: path
        name: holidayId
        required: true
        schema:
          example: 2
          maxLength: 28
          maximum: 28
          minLength: 1
          minimum: 1
          type: integer
  /api/v1/provinces:
    get:
      description: Returns provinces and territories in Canada. Each province or territory lists its associated holidays.
      operationId: get-api-v1-provinces
      parameters:
        - allowEmptyValue: true
          description: A calendar year
          in: query
          name: year
          schema:
            default: '2020'
            maxLength: 4
            minLength: 4
            pattern: '^\d{4}$'
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                /provinces:
                  value:
                    provinces:
                      - holidays:
                          - date: '2020-01-01'
                            federal: 1
                            id: 1
                            nameEn: New Year’s Day
                            nameFr: Jour de l’An
                          - date: '2020-02-17'
                            federal: 0
                            id: 4
                            nameEn: Family Day
                            nameFr: Fête de la famille
                        id: AB
                        nameEn: Alberta
                        nameFr: Alberta
                        nextHoliday:
                          date: '2020-05-18'
                          federal: 1
                          id: 11
                          nameEn: Victoria Day
                          nameFr: Fête de la Reine
                      - holidays:
                          - date: '2020-01-01'
                            federal: 1
                            id: 1
                            nameEn: New Year’s Day
                            nameFr: Jour de l’An
                          - date: '2020-02-17'
                            federal: 0
                            id: 4
                            nameEn: Family Day
                            nameFr: Fête de la famille
                        id: BC
                        nameEn: British Columbia
                        nameFr: Colombie-Britannique
                        nextHoliday:
                          date: '2020-05-18'
                          federal: 1
                          id: 11
                          nameEn: Victoria Day
                          nameFr: Fête de la Reine
              schema:
                properties:
                  provinces:
                    items:
                      $ref: '#/components/schemas/Province'
                    type: array
                type: object
          description: OK
          headers: {}
      summary: Get all provinces
      tags:
        - provinces
  '/api/v1/provinces/{provinceId}':
    get:
      description: Returns a Canadian province or territory with its associated holidays.
      operationId: get-api-v1-provinces-provinceId
      parameters:
        - allowEmptyValue: true
          description: A calendar year
          in: query
          name: year
          schema:
            default: '2020'
            maxLength: 4
            minLength: 4
            pattern: '^\d{4}$'
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                /provinces/MB:
                  value:
                    province:
                      holidays:
                        - date: '2020-01-01'
                          federal: 1
                          id: 1
                          nameEn: New Year’s Day
                          nameFr: Jour de l’An
                        - date: '2020-02-17'
                          federal: 0
                          id: 2
                          nameEn: Louis Riel Day
                          nameFr: Journée Louis Riel
                      id: MB
                      nameEn: Manitoba
                      nameFr: Manitoba
                      nextHoliday:
                        date: '2020-05-18'
                        federal: 1
                        id: 11
                        nameEn: Victoria Day
                        nameFr: Fête de la Reine
              schema:
                properties:
                  province:
                    $ref: '#/components/schemas/Province'
                type: object
          description: OK
          headers: {}
        '404':
          content:
            application/json:
              examples:
                /holidays/100:
                  value:
                    error:
                      message: 'Error: No holiday with id “100”'
                      status: 404
                      timestamp: '2020-04-27T05:41:10.710Z'
              schema:
                properties:
                  error:
                    $ref: '#/components/schemas/Error'
                type: object
          description: Not Found
      summary: Get a province or territory by abbreviation
      tags:
        - root
    parameters:
      - description: A Canadian province abbreviation
        in: path
        name: provinceId
        required: true
        schema:
          enum:
            - AB
            - BC
            - MB
            - NB
            - NL
            - NS
            - NT
            - NU
            - 'ON'
            - PE
            - QC
            - SK
            - YT
          example: MB
          type: string
components:
  schemas:
    Error:
      properties:
        message:
          description: An error message
          example: 'Error: No holiday with id “100”'
          type: string
        status:
          description: An HTTP status code
          example: 404
          maximum: 599
          minimum: 100
          type: integer
        timestamp:
          description: A UTC ISO timestamp
          example: '2020-04-27T05:41:10.710Z'
          format: date-time
          type: string
      title: Error
      type: object
      x-examples:
        /holidays/100:
          message: 'Error: No holiday with id “100”'
          status: 404
          timestamp: '2020-04-27T05:41:10.710Z'
    Holiday:
      description: 'A Canadian holiday. Includes a name, date, and a list of regions that observe this holiday.'
      properties:
        date:
          description: ISO date
          example: '2020-02-17'
          format: date
          type: string
        federal:
          description: Whether this holiday is observed by federally-regulated industries.
          enum:
            - '0'
            - '1'
            - 'true'
            - 'false'
          format: binary
          type: string
        id:
          description: Primary key for a holiday
          example: 2
          maximum: 28
          minimum: 1
          type: integer
        name Fr:
          description: French name
          example: Journée Louis Riel
          type: string
        nameEn:
          description: English name
          example: Louis Riel Day
          type: string
        provinces:
          items:
            $ref: '#/components/schemas/Province'
          type: array
      title: Holiday
      type: object
      x-examples:
        /holidays/2:
          date: '2020-02-17'
          federal: 0
          id: 2
          nameEn: Louis Riel Day
          nameFr: Journée Louis Riel
          provinces:
            - id: MB
              nameEn: Manitoba
              nameFr: Manitoba
    Province:
      description: 'A Canadian province or territory '
      properties:
        id:
          description: Canadian province abbreviations
          enum:
            - AB
            - BC
            - MB
            - NB
            - NL
            - NS
            - NT
            - NU
            - 'ON'
            - PE
            - QC
            - SK
            - YT
          example: MB
          type: string
        nameEn:
          description: English name
          example: Manitoba
          type: string
        nameFr:
          description: French name
          example: Manitoba
          type: string
        nextHoliday:
          $ref: '#/components/schemas/Holiday'
        provinces:
          items:
            $ref: '#/components/schemas/Holiday'
          type: array
      title: Province
      type: object
      x-examples:
        /provinces/MB:
          holidays:
            - date: '2020-01-01'
              federal: 1
              id: 1
              nameEn: New Year’s Day
              nameFr: Jour de l’An
            - date: '2020-02-17'
              federal: 0
              id: 2
              nameEn: Louis Riel Day
              nameFr: Journée Louis Riel
            - date: '2020-04-10'
              federal: 1
              id: 7
              nameEn: Good Friday
              nameFr: Vendredi saint
            - date: '2020-05-18'
              federal: 1
              id: 11
              nameEn: Victoria Day
              nameFr: Fête de la Reine
            - date: '2020-07-01'
              federal: 1
              id: 15
              nameEn: Canada Day
              nameFr: Fête du Canada
            - date: '2020-09-07'
              federal: 1
              id: 24
              nameEn: Labour Day
              nameFr: Fête du travail
            - date: '2020-10-12'
              federal: 1
              id: 25
              nameEn: Thanksgiving
              nameFr: Action de grâce
            - date: '2020-12-25'
              federal: 1
              id: 27
              nameEn: Christmas Day
              nameFr: Noël
          id: MB
          nameEn: Manitoba
          nameFr: Manitoba
          nextHoliday:
            date: '2020-05-18'
            federal: 1
            id: 11
            nameEn: Victoria Day
            nameFr: Fête de la Reine
  securitySchemes: {}
